# Generated by Django 4.1.1 on 2022-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subject_course_remove_subject_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='date',
            field=models.DateTimeField(max_length=60),
        ),
    ]
